FROM balenalib/%%BALENA_MACHINE_NAME%%-fedora-node:13-20200405

RUN install_packages \
    bind-utils \
    dbus \
    iptables \
    iputils \
    jq \
    lockfile-progs \
    tc \
    wondershaper

WORKDIR /usr/src/app

COPY actions.sh package.json package-lock.json tsconfig.json ./
COPY ./src ./src
RUN JOBS=max npm ci --unsafe-perm --production && npm cache clean --force 2>/dev/null
RUN npm run build

CMD [ "node", "/usr/src/app/build/src/index.js" ]
