FROM balenalib/%%BALENA_MACHINE_NAME%%-fedora-python:3.7

RUN install_packages \
    bind-utils \
    dbus \
    iptables \
    iputils \
    jq \
    lockfile-progs \
    tc \
    wondershaper

WORKDIR /usr/src/app

COPY entry.sh ./

ENTRYPOINT [ "/usr/src/app/entry.sh" ]
